=== 2BDetermined-7034/2B-QR-Scouting/config/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Config",
  "definitions": {
    "Config": {
      "type": "object",
      "properties": {
        "$schema": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "page_title": {
          "type": "string"
        },
        "year": {
          "type": "string"
        },
        "sections": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Section"
          }
        }
      },
      "required": ["title", "page_title", "year", "sections"],
      "additionalProperties": false
    },
    "Section": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "preserveDataOnReset": {
          "type": "boolean",
          "description": "If true, field data will not be cleared when the scouting form is reset."
        },
        "fields": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/InputProps"
          }
        }
      },
      "required": ["name", "fields"],
      "additionalProperties": false
    },
    "InputProps": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/InputTypes"
        },
        "required": {
          "type": "boolean"
        },
        "code": {
          "type": "string"
        },
        "disabled": {
          "type": "boolean"
        },
        "preserveDataOnReset": {
          "type": "boolean",
          "description": "If true, field data will not be cleared when the scouting form is reset."
        },
        "value": {},
        "choices": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "defaultValue": {},
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        },
        "multiSelect": {
          "type": "boolean"
        },
        "autoIncrementOnReset": {
          "type": "boolean"
        }
      },
      "required": ["title", "type", "required", "code"],
      "additionalProperties": false
    },
    "InputTypes": {
      "type": "string",
      "enum": [
        "text",
        "number",
        "boolean",
        "range",
        "select",
        "counter",
        "image"
      ]
    }
  }
}

=== 2BDetermined-7034/2B-QR-Scouting/config/2024/config.json
{
  "$schema": "../schema.json",
  "title": "QRScout",
  "page_title": "Crescendo",
  "year": "2024",
  "sections": [
    {
      "name": "Prematch",
      "fields": [
        {
          "title": "Scouter Initials",
          "type": "text",
          "required": true,
          "preserveDataOnReset": true,
          "code": "scouter"
        },
        {
          "title": "Match Number",
          "type": "number",
          "required": true,
          "code": "matchNumber",
          "preserveDataOnReset": true,
          "autoIncrementOnReset": true
        },
        {
          "title": "Robot",
          "type": "select",
          "required": true,
          "code": "robot",
          "choices": {
            "R1": "Red 1",
            "R2": "Red 2",
            "R3": "Red 3",
            "B1": "Blue 1",
            "B2": "Blue 2",
            "B3": "Blue 3"
          },
          "defaultValue": "R1"
        },
        {
          "title": "Team Number",
          "type": "number",
          "required": true,
          "code": "teamNumber",
          "preserveDataOnReset": false
        }
      ]
    },
    {
      "name": "Autonomous",
      "preserveDataOnReset": false,
      "fields": [
        {
          "title": "Mobility Point?",
          "type": "boolean",
          "defaultValue": false,
          "required": false,
          "code": "Mved"
        },
        {
          "code": "note#InSpeaker",
          "title": "Notes Scored in Speaker",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "note#InAmp",
          "title": "Notes Scored in Amp",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        }
      ]
    },
    {
      "name": "Teleop",
      "preserveDataOnReset": false,
      "fields": [
        {
          "code": "tspeaker",
          "title": "Notes Scored in Speaker",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "tamp",
          "title": "Notes Scored in Amp",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "ttrap",
          "title": "Notes Scored in Trap",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "Robot Disabled?",
          "title": "Teleop Foul",
          "type": "boolean",
          "defaultValue": false,
          "required": false
        }
      ]
    },
    {
      "name": "Endgame",
      "preserveDataOnReset": false,
      "fields": [
        {
          "title": "Climb?",
          "type": "boolean",
          "required": false,
          "code": "bclimb",
          "defaultValue": false
        },
        {
          "title": "Park?",
          "type": "boolean",
          "required": false,
          "code": "bpark",
          "defaultValue": false
        },
        {
          "title": "Harmonized?",
          "type": "boolean",
          "required": false,
          "code": "harm",
          "defaultValue": false
        },
        {
          "title": "Scored in Trap in Endgame?",
          "type": "boolean",
          "required": false,
          "code": "trap",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "Postmatch",
      "preserveDataOnReset": false,
      "fields": [
        {
          "code": "under",
          "title": "Cycled Under the Stage?",
          "type": "boolean",
          "defaultValue": false,
          "required": false
        },
        {
          "code": "co",
          "title": "Comments",
          "type": "text",
          "min": 0,
          "max": 50,
          "required": true
        }
      ]
    }
  ]
}

=== 2BDetermined-7034/2B-QR-Scouting/config/2025/config.json
{
  "$schema": "../schema.json",
  "title": "QRScout",
  "page_title": "Reefscape",
  "year": "2025",
  "sections": [
    {
      "name": "Prematch",
      "fields": [
        {
          "title": "Scouter Initials",
          "type": "text",
          "required": true,
          "preserveDataOnReset": true,
          "code": "scouter"
        },
        {
          "title": "Match Number",
          "type": "number",
          "required": true,
          "code": "matchNumber",
          "preserveDataOnReset": true,
          "autoIncrementOnReset": true
        },
        {
          "title": "Robot",
          "type": "select",
          "required": true,
          "preserveDataOnReset": true,
          "code": "robot",
          "choices": {
            "R1": "Red 1",
            "R2": "Red 2",
            "R3": "Red 3",
            "B1": "Blue 1",
            "B2": "Blue 2",
            "B3": "Blue 3"
          },
          "defaultValue": "R1"
        },
        {
          "title": "Team Number",
          "type": "number",
          "required": true,
          "code": "teamNumber"
        }
      ]
    },
    {
      "name": "Autonomous",
      "preserveDataOnReset": false,
      "fields": [
        {
          "title": "Left Starting Zone?",
          "type": "boolean",
          "defaultValue": false,
          "required": false,
          "code": "Mved"
        },
        {
          "code": "al4",
          "title": "Coral in L4",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "al3",
          "title": "Coral in L3",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "al2",
          "title": "Coral in L2",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "al1",
          "title": "Coral in L1",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "aprocessor",
          "title": "Algae in Processor",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "anet",
          "title": "Algae in Processor",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        }
      ]
    },
    {
      "name": "Teleop",
      "preserveDataOnReset": false,
      "fields": [
        {
          "code": "tl4",
          "title": "Coral in L4",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "tl3",
          "title": "Coral in L3",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "tl2",
          "title": "Coral in L2",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "tl1",
          "title": "Coral in L1",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "tprocesser",
          "title": "Algae in processor",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "tnet",
          "title": "Algae in net",
          "type": "counter",
          "defaultValue": 0,
          "min": 0,
          "required": false
        },
        {
          "code": "Robot Disabled?",
          "title": "Teleop Foul",
          "type": "boolean",
          "defaultValue": false,
          "required": false
        }
      ]
    },
    {
      "name": "Endgame",
      "preserveDataOnReset": false,
      "fields": [
        {
          "title": "Shallow Climb",
          "type": "boolean",
          "required": false,
          "code": "sclimb",
          "defaultValue": false
        },
        {
          "title": "Deep Climb",
          "type": "boolean",
          "required": false,
          "code": "dclimb",
          "defaultValue": false
        },
        {
          "title": "Park",
          "type": "boolean",
          "required": false,
          "code": "park",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "Postmatch",
      "preserveDataOnReset": false,
      "fields": [
        {
          "code": "or",
          "title": "Offense Skill",
          "type": "select",
          "choices": {
            "1": "Not Effective",
            "2": "Average",
            "3": "Very Effective",
            "x": "Not Observed"
          },
          "defaultValue": "x",
          "required": false
        },
        {
          "code": "dr",
          "title": "Defense Skill",
          "type": "select",
          "choices": {
            "1": "Not Effective",
            "2": "Average",
            "3": "Very Effective",
            "x": "Not Observed"
          },
          "defaultValue": "x",
          "required": false
        },
        {
          "code": "ar",
          "title": "Accuracy",
          "type": "select",
          "choices": {
            "1": "Not Accurate",
            "2": "Average",
            "3": "Very Accurate",
            "x": "Not Observed"
          },
          "defaultValue": "x",
          "required": false
        },
        {
          "code": "dto",
          "title": "Died/Tipped Over",
          "type": "boolean",
          "defaultValue": false,
          "required": false
        },
        {
          "code": "yc",
          "title": "Yellow/Red Card",
          "type": "select",
          "defaultValue": "No Card",
          "required": true,
          "choices": {
            "No Card": "No Card",
            "Yellow": "Yellow Card",
            "Red": "Red Card"
          }
        },
        {
          "code": "co",
          "title": "Comments",
          "type": "text",
          "min": 0,
          "max": 300,
          "required": true
        }
      ]
    }
  ]
}
